 [[redirects]]
  from = "/api/*"
  to = "https://yoke-staging.up.railway.app/:splat"
  status = 200
  force = false
  headers = {Access-Control-Allow-Origin = "*"}

 [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200